import json
import os
import requests
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Gemini API info
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY not found in environment variables")

MODEL_NAME = "gemini-2.5-flash"
GEMINI_ENDPOINT = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL_NAME}:generateContent"

# GitHub info
github_token = os.getenv("GITHUB_TOKEN")
repo = os.getenv("GITHUB_REPOSITORY")
event_path = os.getenv("GITHUB_EVENT_PATH")

if not event_path:
    raise RuntimeError("GITHUB_EVENT_PATH not found")

# Load PR event
with open(event_path, "r") as f:
    event = json.load(f)

pr_number = event.get("pull_request", {}).get("number")
if not repo or not pr_number:
    raise RuntimeError("Not running inside a PR workflow")

# Fetch PR files
url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/files"
headers = {
    "Authorization": f"Bearer {github_token}",
    "Accept": "application/vnd.github+json"
}

response = requests.get(url, headers=headers)
files = response.json()

if not isinstance(files, list):
    raise RuntimeError(f"GitHub API error: {files}")

# Aggregate PR diffs
diff_text = ""
for file in files:
    patch = file.get("patch")
    if patch:
        diff_text += f"File: {file.get('filename')}\n{patch}\n\n"

if not diff_text:
    diff_text = "No diff found in this PR."

# Build Gemini prompt
prompt = f"""
You are a senior software engineer conducting a GitHub PR review.
Analyze the following code diff and provide a structured review covering:

1. Bugs & Issues
2. Security Concerns
3. Performance
4. Best Practices
5. Positive Aspects

Code diff:
{diff_text}

Provide actionable recommendations with line references when possible.
"""

payload = {
    "contents": [{"parts": [{"text": prompt}]}],
    "generationConfig": {
        "temperature": 0.4,
        "maxOutputTokens": 4096,
        "topP": 0.95,
        "topK": 40
    },
    "safetySettings": [
        {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
        {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"}
    ]
}

# Call Gemini API
try:
    logger.info("Sending review request to Gemini API...")
    gemini_response = requests.post(
        GEMINI_ENDPOINT,
        headers={"Content-Type": "application/json"},
        params={"key": GEMINI_API_KEY},
        json=payload,
        timeout=60
    )

    if gemini_response.status_code != 200:
        error_detail = gemini_response.json() if gemini_response.text else {"error": "Unknown error"}
        logger.error(f"Gemini API error {gemini_response.status_code}: {error_detail}")
        raise RuntimeError(f"Gemini API error: {error_detail}")

    data = gemini_response.json()
    candidates = data.get("candidates", [])
    if not candidates:
        raise RuntimeError("No review generated by Gemini API")

    content = candidates[0].get("content", {})
    parts = content.get("parts", [])
    review_text = parts[0].get("text", "No review content returned.") if parts else "No review content returned."

except Exception as e:
    review_text = f"⚠️ AI review failed: {e}"

# Post comment to PR
comment_url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
payload = {"body": f"🤖 **AI PR Review (Gemini)**:\n\n{review_text}"}

post = requests.post(comment_url, headers=headers, json=payload)
if post.status_code == 201:
    logger.info(f"✅ Comment posted successfully on PR #{pr_number}")
else:
    logger.error(f"❌ Failed to post comment. Status code: {post.status_code}, response: {post.text}")
